export enum COLORS {
  MEDIUM_BLUE = '#2BD6FD',
  DARK_BLUE = '#07ADF5',
  LIGHT_BLUE = '#C4EDF6',
  PURPLE = '#DB19FF',
  WHITE = 'white',
  DARK_GRAY = '#76767A',
  MEDIUM_GRAY = '#C6C8CF',
  LIGHT_GRAY = '#f0efef',
  DARK_RED = '#C10303',
  LIGHT_BLACK = '#333233',
  TRANSPARENT = 'transparent',
  BLACK = '#000000',
}

export const GRADIENTS = {
  PURPLE_BLUE: [COLORS.PURPLE, COLORS.MEDIUM_BLUE],
};
