export enum ROUTES {
  // ROOT STACK
  AUTHENTICATION = 'AUTHENTICATION',
  DASHBOARD = 'DASHBOARD',

  // AUTHENTICATION
  LOGIN = 'LOGIN',

  // DASHBOARD
  CUISINES = 'CUISINES',
  RESTAURANTS = 'RESTAURANTS',
  DETAIL = 'DETAIL',
}
